### ISSUE TITLE
July 2015 Usage

### ISSUE THREAD

**Issue by patwater** [CityofSantaMonica/WaterUsage#2]
There's no usage (data :P ) in July 2015: https://demo.californiadatacollaborative.com/smc/rate-tool/

:(

**Comment by thekaveman** [comment]
Hi @patwater - we can't speak to that tool, as the City of Santa Monica didn't develop it. You can view our full dataset here: https://data.smgov.net/Public-Services/Water-Usage/4nnq-5vzx (which does include usage information for July 2015).

**Comment by patwater** [comment]
Ah thanks much and likely the data was updated since our data team inputed that into the rate tool.  Cheers

**Comment by thekaveman** [comment]
Let us know if you have any other questions or if you find that the data is out of date in our source.
